### ISSUE TITLE
Frameless windows do not work

### ISSUE THREAD

**Issue by probablykasper** [goabstract/electron-panel-window#3]
When I add `frame: false` to `PanelWindow`'s options, the window never appears. It removes the ability to type in the active application, and then nothing else happens.

Example, where Electron 4.2.5 is used:
```js
const { app } = require('electron');
const { PanelWindow } = require('electron-panel-window');

app.on('ready', function() {
	const win = new PanelWindow({
		width: 700,
		backgroundColor: '#FF0000',
		height: 200,
		show: false,
		center: true,
		// frame: false,
	});
	win.show();
});
```

**Comment by kasper9n** [comment]
On a side-note, really thankful for you putting the effort into this, @tommoor!

**Comment by skinner2401** [comment]
I am running into this issue as well.

As soon as I attempt to set a frame to false, no browser window.  Granted, I had to rebuild for electron v6.0.0, but the issue still stands.

**Comment by davidmerfield** [comment]
You don't need to pass `frame: false` to get a frameless window. This should probably be documented, or a warning should be logged when you attempt to do this.

For example:

![image](https://user-images.githubusercontent.com/747928/77929972-46577480-7278-11ea-89d5-b42157dc1cf8.png)

_index.js_
```js
const app = require('electron').app;
const PanelWindow = require('electron-panel-window').PanelWindow;

app.on('ready', function () {
  let mainWindow = new PanelWindow({
    center: true,
    width: 500,
    height: 200,
    minHeight: 100,
    minWidth: 100,
    show: false
  });
  mainWindow.loadURL('file://' + __dirname + '/index.html')
  mainWindow.on('ready-to-show',function() {
    mainWindow.show();
  });
});
```

_index.html_
```html
<html>
  <head><meta charset="UTF-8"><title>Test</title></head>
  <style>body {background: gold}</style>
  <body>Test</body>
</html>
```

Thanks for a fantastic library @tommoor! cc: @probablykasper @skinner2401

**Comment by kasper9n** [comment]
@davidmerfield You're absolutely right, I got it working.

Unfortunately, I still can't use it because the PanelWindow blur event doesn't work for me (#4). If you ever find a solution or alternative, do tell me

**Comment by harshitsilly** [comment]
i got it working with frame as option for electron version 7.1.12
